name: 'Apex Up'
description: 'Deploy & manage Up applications'
inputs:
  stage:
    description: 'Up stage to deploy'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stage }}
branding:
  icon: 'chevron-up'
  color: 'white'